import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Course App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  );
}
